apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ray-operator
spec:
  destination:
    namespace: ray-operator
    server: https://kubernetes.default.svc
  project: ray-io
  source:
    chart: kuberay-operator
    helm:
      values: |-
        env:
          - name: ENABLE_INIT_CONTAINER_INJECTION
            value: "false"
    repoURL: https://ray-project.github.io/kuberay-helm/
    targetRevision: 1.2.2
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ray-cluster
spec:
  destination:
    namespace: ray-operator
    server: https://kubernetes.default.svc
  project: ray-io
  source:
    chart: ray-cluster
    helm:
      parameters:
        - name: additionalWorkerGroups.smallGroup.disabled
          value: 'false'
    repoURL: https://ray-project.github.io/kuberay-helm/
    targetRevision: 1.2.2
  syncPolicy:
    syncOptions:
      - ServerSideApply=true