---
apiVersion: content.hauler.cattle.io/v1alpha1
kind: Charts
metadata:
  name: rancher-airgap-charts
spec:
  charts:
    - name: rancher
      repoURL: https://releases.rancher.com/server-charts/latest
      version: 2.9.2
---
# curl -sL "https://github.com/rancher/rancher/releases/download/v2.9.2/rancher-images.txt" | grep 'rancher/rancher' >> rancher-application.yaml
apiVersion: content.hauler.cattle.io/v1alpha1
kind: Images
metadata:
  name: airgap-images-rancher
spec:
  images:
      - name: rancher/rancher-agent:v2.9.2
        platform: linux/amd64
      - name: rancher/rancher-csp-adapter:v4.0.0
        platform: linux/amd64
      - name: rancher/rancher-webhook:v0.5.2
        platform: linux/amd64
      - name: rancher/rancher:v2.9.2
        platform: linux/amd64
---
# curl -sL "https://github.com/rancher/rancher/releases/download/v2.9.2/rancher-images.txt" | grep 'mirrored-metr' >> rancher-application.yaml
# curl -sL "https://github.com/rancher/rancher/releases/download/v2.9.2/rancher-images.txt" | grep 'mirrored-prom' >> rancher-application.yaml
apiVersion: content.hauler.cattle.io/v1alpha1
kind: Images
metadata:
  name: airgap-images-monitoring
spec:
  images:
      - name: rancher/mirrored-prometheus-adapter-prometheus-adapter:v0.12.0
        platform: linux/amd64
      - name: rancher/mirrored-prometheus-alertmanager:v0.27.0
        platform: linux/amd64
      - name: rancher/mirrored-prometheus-node-exporter:v1.7.0
        platform: linux/amd64
      - name: rancher/mirrored-prometheus-operator-admission-webhook:v0.72.0
        platform: linux/amd64
      - name: rancher/mirrored-prometheus-operator-prometheus-config-reloader:v0.72.0
        platform: linux/amd64
      - name: rancher/mirrored-prometheus-operator-prometheus-operator:v0.72.0
        platform: linux/amd64
      - name: rancher/mirrored-prometheus-prometheus:v2.50.1
        platform: linux/amd64
      - name: rancher/mirrored-prometheus-windows-exporter:0.25.1
      - name: rancher/mirrored-metrics-server:v0.6.3
        platform: linux/amd64
      - name: rancher/mirrored-metrics-server:v0.7.0
        platform: linux/amd64
      - name: rancher/mirrored-metrics-server:v0.7.1
        platform: linux/amd64
---
# curl -sL "https://github.com/rancher/rancher/releases/download/v2.9.2/rancher-images.txt" | grep 'mirrored-library' >> rancher-application.yaml
apiVersion: content.hauler.cattle.io/v1alpha1
kind: Images
metadata:
  name: airgap-images-library
spec:
  images:
      - name: rancher/mirrored-library-busybox:1.31.1
        platform: linux/amd64
      - name: rancher/mirrored-library-busybox:1.34.1
        platform: linux/amd64
      - name: rancher/mirrored-library-busybox:1.36.1
        platform: linux/amd64
      - name: rancher/mirrored-library-nginx:1.24.0-alpine
        platform: linux/amd64
      - name: rancher/mirrored-library-traefik:2.10.5
        platform: linux/amd64
      - name: rancher/mirrored-library-traefik:2.10.7
        platform: linux/amd64
      - name: rancher/mirrored-library-traefik:2.9.10
        platform: linux/amd64