---
apiVersion: content.hauler.cattle.io/v1alpha1
kind: Charts
metadata:
  name: airgap-charts-smb
spec:
  charts:
    - name: csi-driver-smb
      repoURL: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts
      version: v1.14.0
---
apiVersion: content.hauler.cattle.io/v1alpha1
kind: Images
metadata:
  name: airgap-images-smb
spec:
  images:
    - name: registry.k8s.io/sig-storage/livenessprobe:v2.12.0
    - name: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.10.0
    - name: registry.k8s.io/sig-storage/smbplugin:v1.14.0
    - name: registry.k8s.io/sig-storage/csi-provisioner:v4.0.0
    - name: registry.k8s.io/sig-storage/livenessprobe:v2.12.0
    - name: registry.k8s.io/sig-storage/smbplugin:v1.14.0